http:
  port: 45680
  adminPort: 45681

logging:
  console:
    enabled: true
    threshold: DEBUG

catalogServiceHost: dev-catalog-service.clearstorydatainc.com
catalogServicePort: 6789
superUserId: 70094664-1b93-49c1-aeac-7b2c6257eb5f

s3Config:
  bucketName: test-agent-clearstorydata
  accessKey: AKIAIGAWQF6TRKICUJEA
  secretKey: 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
